@echo off
echo Starting Remote Patient Monitoring System...
echo Launching backend and frontend dev servers in a split Windows Terminal...

wt -d "%~dp0backend" cmd /k "call "%~dp0venv\Scripts\activate" && uvicorn main:app --reload" ";" split-pane -d "%~dp0frontend" cmd /k "npm run dev"
